# netlify.toml
[build]
    publish = "public"
    command = "hugo --gc --minify"

[context.production.environment]
    HUGO_VERSION = "v0.107.0"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"